force-app/main/default/objects/LWC_Chat__e/LWC_Chat__e.object-meta.xml
<CustomObject>
    <label>LWC Chat</label>
    <pluralLabel>LWC Chat</pluralLabel>
</CustomObject>

force-app/main/default/objects/LWC_Chat__e/fields/ChatUserId__c.field-meta.xml
<CustomField>
    <fullName>ChatUserId__c</fullName>
    <description>user connection id</description>
    <label>ChatUserId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LWC_Chat__e/fields/ChatUserName__c.field-meta.xml
<CustomField>
    <fullName>ChatUserName__c</fullName>
    <description>Chat user name</description>
    <label>ChatUserName</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LWC_Chat__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>message content</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LWC_Chat__e/fields/MessageType__c.field-meta.xml
<CustomField>
    <fullName>MessageType__c</fullName>
    <description>join, leave, comment...</description>
    <label>MessageType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LWC_Chat__e/fields/ProfileImageType__c.field-meta.xml
<CustomField>
    <fullName>ProfileImageType__c</fullName>
    <description>url or color</description>
    <label>ProfileImageType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LWC_Chat__e/fields/ProfileImageValue__c.field-meta.xml
<CustomField>
    <fullName>ProfileImageValue__c</fullName>
    <description>User profile image url or color code</description>
    <label>ProfileImageValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcPlatformEventChatController.cls
public with sharing class LwcPlatformEventChatController {
  @AuraEnabled(cacheable=true)
  public static User getUserData() {
    return [
      SELECT Id, Name, SmallPhotoUrl
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];
  }

  @AuraEnabled
  public static void publish(
    String userId,
    String userName,
    String messageType,
    String message,
    String profileType,
    String profileValue
  ) {
    List<LWC_Chat__e> events = new List<LWC_Chat__e>();
    events.add(
      new LWC_Chat__e(
        MessageType__c = messageType,
        Message__c = message,
        ChatUserId__c = userId,
        ChatUserName__c = userName,
        ProfileImageValue__c = profileValue,
        ProfileImageType__c = profileType
      )
    );

    // Call method to publish events
    List<Database.SaveResult> results = EventBus.publish(events);

    // Inspect publishing result for each event
    for (Database.SaveResult sr : results) {
      if (sr.isSuccess()) {
        // System.debug('Successfully published event.');
      } else {
        for (Database.Error err : sr.getErrors()) {
          System.debug(
            'Error returned: ' +
            err.getStatusCode() +
            ' - ' +
            err.getMessage()
          );
        }
      }
    }
  }
}